# Emit a probe project that instantiates every scheme in the table, so that a
# wrong type string or a missing header fails to compile instead of sitting in
# the table unnoticed.
#
# Run standalone to inspect the generated sources:
#     julia --project=. test/gen_probe.jl [outdir]
#
# The test suite calls `generate_probe` and then builds the result.

using DiFfRG

"""
    generate_probe(outdir) -> Int

Write a compilable project instantiating every legal (discretization, stepper)
pair in the scheme table. Returns the number of combinations emitted.
"""
function generate_probe(OUT::AbstractString)
mkpath(OUT)

table = load_schemes()
fem = [d for (d, e) in table["discretizations"] if e["main_shape"] == "fem"]
steppers = sort(collect(keys(table["steppers"])))
sort!(fem)

# One model for the FEM family, one for the pure-variables assembler.
write(joinpath(OUT, "model.hh"), """
#pragma once
#include <DiFfRG/model/model.hh>
using namespace DiFfRG;

using FEFunctionDesc = FEFunctionDescriptor<Scalar<"u">>;
using Components = ComponentDescriptor<FEFunctionDesc>;
constexpr auto idxf = FEFunctionDesc{};

class ProbeModel : public def::AbstractModel<ProbeModel, Components>,
                   public def::fRG,
                   public def::LLFFlux<ProbeModel>,
                   public def::FlowBoundaries<ProbeModel>,
                   public def::AD<ProbeModel>
{
public:
  static constexpr uint dim = 1;
  ProbeModel() : def::fRG(1.) {}

  template <typename Vector> void initial_condition(const Point<dim> &pos, Vector &values) const
  {
    values[idxf("u")] = pos[0];
  }

  template <typename NT, typename Solution>
  void flux(std::array<Tensor<1, dim, NT>, Components::count_fe_functions(0)> &flux,
            const Point<dim> &, const Solution &sol) const
  {
    const auto &fe_functions = get<"fe_functions">(sol);
    flux[idxf("u")][0] = 0.5 * powr<2>(fe_functions[idxf("u")]);
  }
};

using VarDesc = VariableDescriptor<Scalar<"A">>;
using VarComponents = ComponentDescriptor<FEFunctionDescriptor<>, VarDesc>;
constexpr auto idxv = VarDesc{};

class ProbeVariablesModel : public def::AbstractModel<ProbeVariablesModel, VarComponents>,
                            public def::fRG,
                            public def::NoJacobians
{
public:
  static constexpr uint dim = 0;
  ProbeVariablesModel() : def::fRG(1.) {}

  template <typename Vector> void initial_condition_variables(Vector &values) const
  {
    values[idxv("A")] = 1.;
  }
  template <typename Vector, typename Solution> void dt_variables(Vector &residual, const Solution &sol) const
  {
    residual[idxv("A")] = -get<"variables">(sol)[idxv("A")];
  }
};
""")

lines = String[]
headers = String[]
combos = 0
skipped = String[]

for disc in fem, stepper in steppers
    entry = table["steppers"][stepper]
    # These aliases have no default for their extra parameters; the table says
    # so, and resolve_scheme supplies one.
    solver = entry["linear_solver"] == "required" ? "UMFPack" : nothing
    local scheme
    try
        scheme = resolve_scheme(; model = "ProbeModel", dim = 1, discretization = disc,
                                stepper = stepper, linear_solver = solver)
    catch err
        push!(skipped, "$disc + $stepper: $(sprint(showerror, err))")
        continue
    end
    combos += 1
    tag = "$(disc)_$(stepper)"
    append!(headers, scheme.headers)
    push!(lines, "using Disc_$tag = $(scheme.discretization);")
    push!(lines, "using Asm_$tag  = $(scheme.assembler);")
    push!(lines, "using Step_$tag = $(scheme.stepper);")
    push!(lines, "static_assert(sizeof(Asm_$tag) > 0, \"$tag assembler\");")
    push!(lines, "static_assert(sizeof(Step_$tag) > 0, \"$tag stepper\");")
    push!(lines, "")
end

for stepper in steppers
    entry = table["steppers"][stepper]
    solver = entry["linear_solver"] == "required" ? "UMFPack" : nothing
    local scheme
    try
        scheme = resolve_scheme(; model = "ProbeVariablesModel", dim = 0,
                                discretization = "Variables", stepper = stepper,
                                linear_solver = solver)
    catch err
        push!(skipped, "Variables + $stepper: $(sprint(showerror, err))")
        continue
    end
    combos += 1
    tag = "Variables_$stepper"
    append!(headers, scheme.headers)
    push!(lines, "using Asm_$tag  = $(scheme.assembler);")
    push!(lines, "using Step_$tag = $(scheme.stepper);")
    push!(lines, "static_assert(sizeof(Asm_$tag) > 0, \"$tag assembler\");")
    push!(lines, "")
end

seen = String[]
for h in headers
    h in seen || push!(seen, h)
end

open(joinpath(OUT, "probe.cc"), "w") do io
    println(io, "// Generated by test/gen_probe.jl -- do not edit.")
    println(io, "// Instantiates every scheme in frontend/schemes.toml.")
    for h in seen
        println(io, "#include <", h, ">")
    end
    println(io, "#include <DiFfRG/DiFfRG.hh>")
    println(io, "#include \"model.hh\"")
    println(io, "\nusing namespace DiFfRG;\n")
    foreach(l -> println(io, l), lines)
    println(io, "int main() { return 0; }")
end

write(joinpath(OUT, "CMakeLists.txt"), """
cmake_minimum_required(VERSION 3.27.0)
project(schemes_probe)
find_package(DiFfRG REQUIRED HINTS \$ENV{HOME}/.local/share/DiFfRG/)
add_executable(schemes_probe probe.cc)
target_link_libraries(schemes_probe PRIVATE DiFfRG::DiFfRG)
""")

println("wrote $OUT: $combos combinations, $(length(seen)) headers")
isempty(skipped) || (println("skipped:"); foreach(s -> println("  ", s), skipped))
return combos
end

# Standalone invocation.
if abspath(PROGRAM_FILE) == @__FILE__
    generate_probe(abspath(get(ARGS, 1, mktempdir(; prefix = "diffrg_probe_", cleanup = false))))
end
