if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.31.0")
  cmake_policy(SET CMP0177 NEW)
endif()

install(
  DIRECTORY ${CMAKE_SOURCE_DIR}/../python
  DESTINATION ./
  MESSAGE_NEVER)
install(
  DIRECTORY ${CMAKE_SOURCE_DIR}/../Mathematica
  DESTINATION ./
  MESSAGE_NEVER)
