(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
TBAutoDefine["AAA2"]=True;

TBRequiredGroups["AAA2"]={{color,SUNfund,Nc}};

TBVertex["AAA2"]={A,A,A};

TBVertexBasis["AAA2"]=True;

TBComment["AAA2"]="Three-gluon vertex basis";

TBAuthor["AAA2"]="FR Sattler";

TBUsage["AAA2"]={"Indices: 
	A: {\!\(\*SubscriptBox[\(p\), \(1\)]\),\[Mu],\!\(\*SubscriptBox[\(a\), \(1\)]\)}
	A: {\!\(\*SubscriptBox[\(p\), \(2\)]\),\[Nu],\!\(\*SubscriptBox[\(a\), \(2\)]\)}
	A: {\!\(\*SubscriptBox[\(p\), \(3\)]\),\[Rho],\!\(\*SubscriptBox[\(a\), \(3\)]\)}
We use the general form 
	\[ScriptCapitalL] = (2\[Pi]\!\(\*SuperscriptBox[\()\), \(d\)]\)\[Delta](\!\(\*SubscriptBox[\(p\), \(1\)]\)+\!\(\*SubscriptBox[\(p\), \(2\)]\)+\!\(\*SubscriptBox[\(p\), \(3\)]\))\!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\)
and the \!\(\*SubscriptBox[\(\[Tau]\), \(i\)]\) are listed in the following:    ",
TableForm[
{
{"\!\(\*SuperscriptBox[\(f\), \(\*SubscriptBox[\(a\), \(1\)] \*SubscriptBox[\(a\), \(2\)] \*SubscriptBox[\(a\), \(3\)]\)]\)\!\(\*SubscriptBox[\(\[Delta]\), \(\[Mu]\[Nu]\)]\)(\!\(\*SubscriptBox[\(p\), \(2\)]\)-\!\(\*SubscriptBox[\(p\), \(1\)]\)\!\(\*SubscriptBox[\()\), \(\[Rho]\)]\)"}
},TableHeadings->{{1}, {"Tensor"}},TableSpacing->{3, 3}]
};

TBIndices["AAA2"]={{p1,mu,a1},{p2,nu,a2},{p3,rho,a3}};

TBMomentumConservation["AAA2"]={(*p3->-p1-p2*)};

TBBasis["AAA2"]={
	I TBF[color,a1,a2,a3] (TBdeltaLorentz[mu,nu]TBvec[p2-p1,rho] +TBdeltaLorentz[mu,rho] TBvec[p1-p3,nu] +TBdeltaLorentz[nu,rho]TBvec[p3-p2,mu])
	(*T^(1)*)(*,

	1/6\[ImaginaryI] TBF[color,a1,a2,a3] (TBvec[q1,mu]TBvec[q2,nu]TBvec[q3,rho])
	(*T^(2)*),

	1/6\[ImaginaryI] TBF[color,a1,a2,a3] (TBvec[p1,mu]TBvec[p2,nu]TBvec[p3,rho])
	(*T^(3)*),

	1/6\[ImaginaryI] TBF[color,a1,a2,a3] (TBvec[q1,mu]TBvec[q2,nu]TBvec[p3,rho])
	(*T^(4)*)*)
}//.{q1->p2-p3,q2->p3-p1,q3->p1-p2};

TBCanonicalProduct["AAA2"]=Tensor1[1,2,3]Tensor2[1,2,3];



