# ##############################################################################
# Regression tests
# ##############################################################################

setup_test(gross_neveu_kt_regression.cc)
setup_test(on_model_kt_regression.cc)
add_subdirectory(on_model_kt_3D)
setup_test(quark_meson_kt_regression.cc)
