"""
Writing a model, a driver, a build file and a parameter file to disk.

The result is an ordinary DiFfRG app -- the same three files a user would write
by hand -- so it builds, runs and is read back through exactly the same path as
a hand-written one, and can be inspected or taken over if the generator runs out
of road.
"""

# The bases a model gets when it does not name them. Which boundary stencil and
# whether a numerical flux is needed are properties of the scheme, so both come
# from the table rather than from a rule spelled out here.
function _default_mixins(table, discretization)
    disc = table["discretizations"][discretization]
    # No field space, so no flux, no boundaries, and nothing for the FE
    # jacobians to differentiate.
    disc["main_shape"] == "variables" && return ["fRG", "NoJacobians"]
    mixins = ["fRG"]
    get(disc, "numflux", false) && push!(mixins, "LLFFlux")
    push!(mixins, "AD")
    haskey(disc, "default_boundary") && push!(mixins, disc["default_boundary"])
    return mixins
end

"""
    resolve_mixins(model, scheme; table) -> (types, headers)

The CRTP base list for a model, as C++ type strings.

Rejects two mixins claiming the same role -- two jacobian strategies, say --
which would otherwise be an ambiguous-base error deep in a template.
"""
function resolve_mixins(model::Model, discretization::AbstractString; table)
    names = isempty(model.mixins) ? _default_mixins(table, discretization) : model.mixins
    types, headers = String[], String[]
    seen = Dict{String,String}()
    for name in names
        haskey(table["mixins"], name) ||
            throw(ArgumentError("unknown mixin $(repr(name)); have " *
                                join(sort(collect(keys(table["mixins"]))), ", ")))
        entry = table["mixins"][name]
        role = entry["category"]
        if haskey(seen, role)
            throw(ArgumentError("mixins $(seen[role]) and $name both provide '$role'; " *
                                "a model may have only one"))
        end
        seen[role] = name
        subs = Dict("model" => model.name)
        if get(entry, "takes_component", false)
            model.constraint_component === nothing &&
                throw(ArgumentError("mixin $name needs a component; pass constraint_component="))
            subs["component"] = model.constraint_component
        end
        push!(types, _fill(entry["type"], subs))
        append!(headers, String.(entry["headers"]))
    end
    return types, headers
end

# Written as a double unless the value is genuinely integral: the C++ side reads
# each key with a typed getter, so `Nc = 3` must not become get_double.
_param_kind(v::Bool) = ("bool", "get_bool")
_param_kind(v::Integer) = ("int", "get_int")
_param_kind(v::Real) = ("double", "get_double")
_param_kind(v::Union{AbstractString,Symbol}) = ("std::string", "get_string")
_param_kind(v) = throw(ArgumentError("cannot emit a parameter of type $(typeof(v))"))

"""
    emit_parameters(model) -> String

The `Parameters` struct, reading each key from `/physical`.

This is the boilerplate a hand-written model repeats three times per key -- in
the member list, in the constructor and in the parameter file -- and gets
subtly wrong when a `double` is read with `get_int`.
"""
function emit_parameters(model::Model)
    isempty(model.params) && return ""
    io = IOBuffer()
    println(io, "struct Parameters {")
    println(io, "  Parameters(const ConfigTree &config)")
    println(io, "  {")
    for (k, v) in model.params
        println(io, "    $k = config.$(_param_kind(v)[2])(\"/physical/$k\");")
    end
    println(io, "  }")
    println(io)
    for (k, v) in model.params
        println(io, "  $(_param_kind(v)[1]) $k;")
    end
    println(io, "};")
    return String(take!(io))
end

_descriptor(kind, comps) =
    "$kind<" * join((cxx_type(c) for c in comps), ", ") * ">"

"""
    emit_model(model, scheme; table) -> String

The complete `model.hh`.
"""
function emit_model(model::Model, scheme::Scheme; table)
    mixins, mixin_headers = resolve_mixins(model, scheme.name; table = table)
    io = IOBuffer()

    println(io, "// Generated by DiFfRG.jl -- edit the Julia model, not this file.")
    println(io, "#pragma once\n")
    for h in unique(vcat(["DiFfRG/model/model.hh", "DiFfRG/physics/physics.hh"],
                         mixin_headers, model.includes))
        println(io, "#include <", h, ">")
    end
    model.flows === nothing || println(io, "#include \"flows/flows.hh\"")
    println(io, "\nusing namespace DiFfRG;\n")
    isempty(model.preamble) || println(io, model.preamble, "\n")

    print(io, emit_parameters(model))
    println(io)

    println(io, "using FEFunctionDesc = ", _descriptor("FEFunctionDescriptor", model.fe), ";")
    isempty(model.variables) ||
        println(io, "using VariableDesc = ", _descriptor("VariableDescriptor", model.variables), ";")
    isempty(model.extractors) ||
        println(io, "using ExtractorDesc = ", _descriptor("ExtractorDescriptor", model.extractors), ";")

    # ComponentDescriptor is positional, so an empty middle slot still has to be
    # spelled out when extractors follow it.
    parts = ["FEFunctionDesc"]
    if !isempty(model.extractors)
        push!(parts, isempty(model.variables) ? "VariableDescriptor<>" : "VariableDesc")
        push!(parts, "ExtractorDesc")
    elseif !isempty(model.variables)
        push!(parts, "VariableDesc")
    end
    println(io, "using Components = ComponentDescriptor<", join(parts, ", "), ">;\n")

    println(io, "constexpr auto idxf = FEFunctionDesc{};")
    isempty(model.variables) || println(io, "constexpr auto idxv = VariableDesc{};")
    isempty(model.extractors) || println(io, "constexpr auto idxe = ExtractorDesc{};")
    println(io)

    # Continuation lines align under the first base, as a hand-written model does.
    indent = " "^length("class $(model.name) : ")
    println(io, "class ", model.name, " : public def::AbstractModel<", model.name, ", Components>,")
    for (i, mx) in enumerate(mixins)
        println(io, indent, "public ", mx, i == length(mixins) ? "" : ",")
    end
    println(io, "{")
    println(io, "public:")
    println(io, "  static constexpr uint dim = ", model.dim, ";\n")

    # Constructor
    inits = String[]
    for mx in mixins
        startswith(mx, "def::fRG") &&
            push!(inits, "def::fRG(config.get_double(\"/physical/Lambda\"))")
    end
    isempty(model.params) || push!(inits, "prm(config)")
    model.flows === nothing || push!(inits, "$(model.flows.member)(config)")
    print(io, "  ", model.name, "(const ConfigTree &config)")
    isempty(inits) || print(io, " : ", join(inits, ", "))
    println(io, " {}\n")

    components = Dict("fe_functions" => [c.name for c in model.fe],
                      "variables" => [c.name for c in model.variables],
                      "extractors" => [c.name for c in model.extractors])
    for (name, sig) in sort(collect(MODEL_MEMBERS); by = first)
        haskey(model.bodies, name) || continue
        body = model.bodies[name]
        code = body isa FlowBody ?
               render_flow(body, components["variables"],
                           model.flows === nothing ? "flow_equations" : model.flows.member) :
               render_body(body, name;
                           components = components, available = scheme.solution)
        println(io, "  ", replace(strip(sig), "\n" => "\n  "))
        println(io, "  {")
        for line in split(rstrip(code), '\n')
            println(io, isempty(strip(line)) ? "" : "    " * lstrip(line, ' '))
        end
        println(io, "  }\n")
    end

    println(io, "private:")
    isempty(model.params) || println(io, "  const Parameters prm;")
    model.flows === nothing ||
        println(io, "  mutable ", model.flows.class, " ", model.flows.member, ";")
    println(io, "};")
    return String(take!(io))
end

"""
    emit_main(model, scheme) -> String

The driver.

Two shapes: the FE one builds a mesh, a discretization and an assembler; the
pure-variables one has no field space and constructs the assembler straight from
the model.
"""
function emit_main(model::Model, scheme::Scheme)
    io = IOBuffer()
    println(io, "// Generated by DiFfRG.jl -- edit the Julia model, not this file.")
    for h in scheme.headers
        println(io, "#include <", h, ">")
    end
    println(io, "#include <DiFfRG/DiFfRG.hh>\n")
    println(io, "#include \"model.hh\"\n")
    println(io, "using namespace dealii;")
    println(io, "using namespace DiFfRG;\n")

    variables_only = scheme.main_shape == "variables"
    println(io, "using Model = ", model.name, ";")
    variables_only || println(io, "constexpr uint dim = Model::dim;")
    variables_only || println(io, "using Mesh = ", scheme.mesh, ";")
    variables_only || println(io, "using Discretization = ", scheme.discretization, ";")
    println(io, "using Assembler = ", scheme.assembler, ";")
    # The stepper is spelled in terms of the alias just declared, as a
    # hand-written driver does, rather than repeating the whole assembler type.
    println(io, "using TimeStepper = ",
            replace(scheme.stepper, scheme.assembler => "Assembler"), ";\n")

    println(io, "int main(int argc, char *argv[])")
    println(io, "{")
    println(io, "  const auto config = DiFfRG::Init(argc, argv).get_configuration_helper().get_config();\n")
    println(io, "  Model model(config);")
    if variables_only
        println(io, "  OutputSession<Assembler> data_out(config);")
        println(io, "  const auto log = data_out.report_port();")
        println(io, "  Assembler assembler(model, config);")
        println(io, "  TimeStepper time_stepper(config, assembler, data_out);\n")
        println(io, "  ", scheme.flowing_variables, " initial_condition;")
    else
        println(io, "  Mesh mesh{Config::ConfigurationMesh<dim>(config)};")
        println(io, "  OutputSession<Assembler> data_out(config);")
        println(io, "  const auto log = data_out.report_port();")
        println(io, "  Discretization discretization(mesh, config, log);")
        println(io, "  Assembler assembler(discretization, model, config);")
        println(io, "  ", scheme.adaptivity_construct)
        println(io, "  TimeStepper time_stepper(config, assembler, data_out, mesh_adaptor);\n")
        println(io, "  ", scheme.flowing_variables, " initial_condition(",
                scheme.flowing_variables_arg, ");")
    end
    println(io, "  initial_condition.interpolate(model);\n")
    println(io, "  Timer timer;")
    println(io, "  try {")
    println(io, "    time_stepper.run(initial_condition, 0., config.get_double(\"/timestepping/final_time\"));")
    println(io, "  } catch (std::exception &e) {")
    println(io, "    log.error(\"Simulation finished with exception {}\", e.what());")
    println(io, "    return -1;")
    println(io, "  }")
    println(io, "  log.info(\"Simulation finished after \" + time_format(timer.wall_time()));")
    println(io, "  return 0;")
    println(io, "}")
    return String(take!(io))
end

"""
    emit_cmake(model) -> String

The build file. Links the generated flow library when the model uses one.
"""
function emit_cmake(model::Model)
    io = IOBuffer()
    println(io, "# Generated by DiFfRG.jl -- edit the Julia model, not this file.")
    println(io, "cmake_minimum_required(VERSION 3.27.0)")
    println(io, "project(", model.name, ")\n")
    println(io, "find_package(DiFfRG REQUIRED HINTS \${DiFfRG_DIR} \$ENV{HOME}/.local/share/DiFfRG/)\n")
    if model.flows !== nothing
        println(io, "add_subdirectory(flows)")
    end
    println(io, "add_executable(", model.name, " ", model.name, ".cc)")
    print(io, "target_link_libraries(", model.name, " PRIVATE DiFfRG::DiFfRG")
    model.flows === nothing || print(io, " ", model.flows.target)
    println(io, ")")
    return String(take!(io))
end

"""
    generate(model, dir; discretization="CG", stepper="SUNDIALS_IDA", config=(), ...) -> App

Write the app to `dir` and return an [`App`](@ref) that builds it.

The output is an ordinary DiFfRG project -- `model.hh`, `<Name>.cc`,
`CMakeLists.txt` and a parameter file -- so it can be built, read and taken over
by hand exactly like one that was written by hand.
"""
function generate(model::Model, dir::AbstractString;
                  discretization::AbstractString = "CG",
                  stepper::AbstractString = "SUNDIALS_IDA",
                  config = (),
                  install::DiFfRGInstall = find_install(),
                  kwargs...)
    table = load_schemes(install)
    scheme = resolve_scheme(; model = model.name, dim = model.dim,
                            discretization = discretization, stepper = stepper,
                            install = install, table = table, kwargs...)

    haskey(model.bodies, "initial_condition") ||
        haskey(model.bodies, "initial_condition_variables") ||
        isempty(model.fe) ||
        throw(ArgumentError("a model with FE functions must define initial_condition; " *
                            "AbstractModel deletes the default"))

    out = abspath(expanduser(String(dir)))
    mkpath(out)
    write(joinpath(out, "model.hh"), emit_model(model, scheme; table = table))
    write(joinpath(out, model.name * ".cc"), emit_main(model, scheme))
    write(joinpath(out, "CMakeLists.txt"), emit_cmake(model))

    if model.flows !== nothing
        dest = joinpath(out, "flows")
        isdir(dest) && rm(dest; recursive = true)
        cp(model.flows.path, dest)
    end

    # No parameter file is written: the app's full schema is whatever the built
    # binary reports, and only the model's own keys and the caller's config are
    # layered onto it. Emitting a partial file here would shadow that schema.
    defaults = Dict{String,Any}("physical" => Dict{String,Any}(
        String(k) => (v isa Symbol ? String(v) : v) for (k, v) in model.params))
    isempty(config) || (defaults = merge_tree(defaults, nest(config)))

    return App(out; target = model.name, install = install, defaults = defaults)
end
